apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinical-summarizer-api
  namespace: clinical-ai
spec:
  template:
    spec:
      nodeSelector:
        accelerator: nvidia-gpu
      containers:
        - name: api
          image: registry.example.local/clinical-summarizer:nvidia-v0.1.0
          env:
            - name: RAG_ORT_EXECUTION_PROVIDER
              value: "CUDAExecutionProvider"
            - name: RAG_WHISPER_DEVICE
              value: "0"
            - name: RAG_VISION_DEVICE
              value: "cuda"
          resources:
            requests:
              cpu: "1000m"
              memory: "4Gi"
              nvidia.com/gpu: "1"
            limits:
              cpu: "4000m"
              memory: "12Gi"
              nvidia.com/gpu: "1"
