"""persistence foundation

Revision ID: b888cb77eb72
Revises: 
Create Date: 2026-05-27 17:31:25.194492
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = 'b888cb77eb72'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_runs',
    sa.Column('model_run_id', sa.Uuid(), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_version', sa.String(length=100), nullable=True),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('prompt_template_id', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=100), nullable=True),
    sa.Column('summary_type', sa.String(length=100), nullable=True),
    sa.Column('context_hash', sa.String(length=255), nullable=True),
    sa.Column('output_hash', sa.String(length=255), nullable=True),
    sa.Column('input_token_count', sa.Integer(), nullable=True),
    sa.Column('output_token_count', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('run_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('model_run_id')
    )
    op.create_table('patients',
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('external_patient_id', sa.String(length=100), nullable=True),
    sa.Column('patient_hash', sa.String(length=255), nullable=True),
    sa.Column('full_name_encrypted', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('phone_encrypted', sa.Text(), nullable=True),
    sa.Column('address_encrypted', sa.Text(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('fhir_patient_id', sa.String(length=100), nullable=True),
    sa.Column('is_deidentified', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('patient_id'),
    sa.UniqueConstraint('patient_hash')
    )
    op.create_index(op.f('ix_patients_external_patient_id'), 'patients', ['external_patient_id'], unique=False)
    op.create_index(op.f('ix_patients_fhir_patient_id'), 'patients', ['fhir_patient_id'], unique=False)
    op.create_table('roles',
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('role_code')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('external_user_id', sa.String(length=100), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['role_code'], ['roles.role_code'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_external_user_id'), 'users', ['external_user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('audit_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('patient_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=True),
    sa.Column('resource_id', sa.Uuid(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_index('idx_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_patient_id'), 'audit_logs', ['patient_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('encounters',
    sa.Column('encounter_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('external_encounter_id', sa.String(length=100), nullable=True),
    sa.Column('fhir_encounter_id', sa.String(length=100), nullable=True),
    sa.Column('encounter_type', sa.String(length=50), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('attending_doctor_id', sa.Uuid(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('reason_for_visit', sa.Text(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['attending_doctor_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('encounter_id')
    )
    op.create_index(op.f('ix_encounters_external_encounter_id'), 'encounters', ['external_encounter_id'], unique=False)
    op.create_index(op.f('ix_encounters_fhir_encounter_id'), 'encounters', ['fhir_encounter_id'], unique=False)
    op.create_index(op.f('ix_encounters_patient_id'), 'encounters', ['patient_id'], unique=False)
    op.create_table('clinical_documents',
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('encounter_id', sa.Uuid(), nullable=True),
    sa.Column('external_document_id', sa.String(length=100), nullable=True),
    sa.Column('fhir_document_reference_id', sa.String(length=100), nullable=True),
    sa.Column('fhir_composition_id', sa.String(length=100), nullable=True),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_title', sa.Text(), nullable=True),
    sa.Column('document_datetime', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author_id', sa.Uuid(), nullable=True),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('raw_text_hash', sa.String(length=255), nullable=True),
    sa.Column('source_file_uri', sa.Text(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('confidentiality_level', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.encounter_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.create_index(op.f('ix_clinical_documents_encounter_id'), 'clinical_documents', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_clinical_documents_external_document_id'), 'clinical_documents', ['external_document_id'], unique=False)
    op.create_index(op.f('ix_clinical_documents_fhir_composition_id'), 'clinical_documents', ['fhir_composition_id'], unique=False)
    op.create_index(op.f('ix_clinical_documents_fhir_document_reference_id'), 'clinical_documents', ['fhir_document_reference_id'], unique=False)
    op.create_index(op.f('ix_clinical_documents_patient_id'), 'clinical_documents', ['patient_id'], unique=False)
    op.create_table('summaries',
    sa.Column('summary_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('encounter_id', sa.Uuid(), nullable=True),
    sa.Column('model_run_id', sa.Uuid(), nullable=True),
    sa.Column('summary_type', sa.String(length=100), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('summary_language', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('draft', 'under_review', 'edited', 'approved', 'rejected', 'archived', name='summary_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('citation_coverage', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('unsupported_claim_count', sa.Integer(), nullable=False),
    sa.Column('conflict_count', sa.Integer(), nullable=False),
    sa.Column('generated_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('approved_by', sa.Uuid(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('parent_summary_id', sa.Uuid(), nullable=True),
    sa.Column('context_hash', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.encounter_id'], ),
    sa.ForeignKeyConstraint(['generated_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.model_run_id'], ),
    sa.ForeignKeyConstraint(['parent_summary_id'], ['summaries.summary_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('summary_id')
    )
    op.create_index('idx_summaries_patient_status', 'summaries', ['patient_id', 'status'], unique=False)
    op.create_index(op.f('ix_summaries_encounter_id'), 'summaries', ['encounter_id'], unique=False)
    op.create_index(op.f('ix_summaries_patient_id'), 'summaries', ['patient_id'], unique=False)
    op.create_table('conditions',
    sa.Column('condition_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('encounter_id', sa.Uuid(), nullable=True),
    sa.Column('external_condition_id', sa.String(length=100), nullable=True),
    sa.Column('fhir_condition_id', sa.String(length=100), nullable=True),
    sa.Column('condition_code', sa.String(length=100), nullable=True),
    sa.Column('coding_system', sa.String(length=100), nullable=True),
    sa.Column('condition_name', sa.Text(), nullable=False),
    sa.Column('clinical_status', sa.String(length=50), nullable=True),
    sa.Column('verification_status', sa.String(length=50), nullable=True),
    sa.Column('onset_date', sa.Date(), nullable=True),
    sa.Column('recorded_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.encounter_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['clinical_documents.document_id'], ),
    sa.PrimaryKeyConstraint('condition_id')
    )
    op.create_index(op.f('ix_conditions_fhir_condition_id'), 'conditions', ['fhir_condition_id'], unique=False)
    op.create_index(op.f('ix_conditions_patient_id'), 'conditions', ['patient_id'], unique=False)
    op.create_table('diagnostic_reports',
    sa.Column('report_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('encounter_id', sa.Uuid(), nullable=True),
    sa.Column('external_report_id', sa.String(length=100), nullable=True),
    sa.Column('fhir_diagnostic_report_id', sa.String(length=100), nullable=True),
    sa.Column('report_type', sa.String(length=100), nullable=True),
    sa.Column('report_title', sa.Text(), nullable=True),
    sa.Column('report_text', sa.Text(), nullable=False),
    sa.Column('conclusion_text', sa.Text(), nullable=True),
    sa.Column('report_status', sa.String(length=50), nullable=True),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.encounter_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['clinical_documents.document_id'], ),
    sa.PrimaryKeyConstraint('report_id')
    )
    op.create_index(op.f('ix_diagnostic_reports_fhir_diagnostic_report_id'), 'diagnostic_reports', ['fhir_diagnostic_report_id'], unique=False)
    op.create_index(op.f('ix_diagnostic_reports_patient_id'), 'diagnostic_reports', ['patient_id'], unique=False)
    op.create_table('document_chunks',
    sa.Column('chunk_id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('encounter_id', sa.Uuid(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(length=255), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('char_start', sa.Integer(), nullable=True),
    sa.Column('char_end', sa.Integer(), nullable=True),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('vector_store', sa.String(length=100), nullable=True),
    sa.Column('chunk_hash', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['clinical_documents.document_id'], ),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.encounter_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.PrimaryKeyConstraint('chunk_id'),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunks_document_index')
    )
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_patient_id'), 'document_chunks', ['patient_id'], unique=False)
    op.create_table('medications',
    sa.Column('medication_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('encounter_id', sa.Uuid(), nullable=True),
    sa.Column('external_medication_id', sa.String(length=100), nullable=True),
    sa.Column('fhir_medication_request_id', sa.String(length=100), nullable=True),
    sa.Column('medication_name', sa.Text(), nullable=False),
    sa.Column('medication_code', sa.String(length=100), nullable=True),
    sa.Column('coding_system', sa.String(length=100), nullable=True),
    sa.Column('dosage_text', sa.Text(), nullable=True),
    sa.Column('route', sa.String(length=100), nullable=True),
    sa.Column('frequency', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('medication_action', sa.String(length=50), nullable=True),
    sa.Column('prescribed_by', sa.Uuid(), nullable=True),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.encounter_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['prescribed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['clinical_documents.document_id'], ),
    sa.PrimaryKeyConstraint('medication_id')
    )
    op.create_index(op.f('ix_medications_fhir_medication_request_id'), 'medications', ['fhir_medication_request_id'], unique=False)
    op.create_index(op.f('ix_medications_patient_id'), 'medications', ['patient_id'], unique=False)
    op.create_table('observations',
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('patient_id', sa.Uuid(), nullable=False),
    sa.Column('encounter_id', sa.Uuid(), nullable=True),
    sa.Column('external_observation_id', sa.String(length=100), nullable=True),
    sa.Column('fhir_observation_id', sa.String(length=100), nullable=True),
    sa.Column('observation_type', sa.String(length=50), nullable=True),
    sa.Column('observation_code', sa.String(length=100), nullable=True),
    sa.Column('coding_system', sa.String(length=100), nullable=True),
    sa.Column('observation_name', sa.Text(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_numeric', sa.Numeric(), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('reference_range_low', sa.Numeric(), nullable=True),
    sa.Column('reference_range_high', sa.Numeric(), nullable=True),
    sa.Column('interpretation', sa.String(length=50), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('source_system', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['encounter_id'], ['encounters.encounter_id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.patient_id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['clinical_documents.document_id'], ),
    sa.PrimaryKeyConstraint('observation_id')
    )
    op.create_index(op.f('ix_observations_fhir_observation_id'), 'observations', ['fhir_observation_id'], unique=False)
    op.create_index(op.f('ix_observations_patient_id'), 'observations', ['patient_id'], unique=False)
    op.create_table('summary_reviews',
    sa.Column('review_id', sa.Uuid(), nullable=False),
    sa.Column('summary_id', sa.Uuid(), nullable=False),
    sa.Column('reviewer_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('start_review', 'edit', 'approve', 'reject', 'comment', name='review_action', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('previous_status', sa.Enum('draft', 'under_review', 'edited', 'approved', 'rejected', 'archived', name='review_previous_summary_status', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('resulting_status', sa.Enum('draft', 'under_review', 'edited', 'approved', 'rejected', 'archived', name='review_resulting_summary_status', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=100), nullable=True),
    sa.Column('edited_summary_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['summary_id'], ['summaries.summary_id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    op.create_index(op.f('ix_summary_reviews_summary_id'), 'summary_reviews', ['summary_id'], unique=False)
    op.create_table('summary_sections',
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('summary_id', sa.Uuid(), nullable=False),
    sa.Column('section_order', sa.Integer(), nullable=False),
    sa.Column('section_title', sa.String(length=255), nullable=False),
    sa.Column('section_text', sa.Text(), nullable=False),
    sa.Column('section_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['summary_id'], ['summaries.summary_id'], ),
    sa.PrimaryKeyConstraint('section_id'),
    sa.UniqueConstraint('summary_id', 'section_order', name='uq_summary_sections_order')
    )
    op.create_index(op.f('ix_summary_sections_summary_id'), 'summary_sections', ['summary_id'], unique=False)
    op.create_table('summary_claims',
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('summary_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=True),
    sa.Column('claim_order', sa.Integer(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('claim_type', sa.String(length=100), nullable=True),
    sa.Column('support_status', sa.Enum('supported', 'unsupported', 'conflicting', 'insufficient_evidence', 'unchecked', name='claim_support_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('clinical_risk_level', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['summary_sections.section_id'], ),
    sa.ForeignKeyConstraint(['summary_id'], ['summaries.summary_id'], ),
    sa.PrimaryKeyConstraint('claim_id'),
    sa.UniqueConstraint('summary_id', 'claim_order', name='uq_summary_claims_order')
    )
    op.create_index(op.f('ix_summary_claims_summary_id'), 'summary_claims', ['summary_id'], unique=False)
    op.create_table('claim_citations',
    sa.Column('citation_id', sa.Uuid(), nullable=False),
    sa.Column('claim_id', sa.Uuid(), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=False),
    sa.Column('source_document_id', sa.Uuid(), nullable=True),
    sa.Column('source_chunk_id', sa.Uuid(), nullable=True),
    sa.Column('source_condition_id', sa.Uuid(), nullable=True),
    sa.Column('source_observation_id', sa.Uuid(), nullable=True),
    sa.Column('source_medication_id', sa.Uuid(), nullable=True),
    sa.Column('source_report_id', sa.Uuid(), nullable=True),
    sa.Column('source_record_type', sa.String(length=100), nullable=True),
    sa.Column('source_record_id', sa.Uuid(), nullable=True),
    sa.Column('source_text_span', sa.Text(), nullable=True),
    sa.Column('source_char_start', sa.Integer(), nullable=True),
    sa.Column('source_char_end', sa.Integer(), nullable=True),
    sa.Column('citation_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('source_document_id IS NOT NULL OR source_chunk_id IS NOT NULL OR source_condition_id IS NOT NULL OR source_observation_id IS NOT NULL OR source_medication_id IS NOT NULL OR source_report_id IS NOT NULL OR source_record_id IS NOT NULL', name='ck_claim_citations_source_required'),
    sa.ForeignKeyConstraint(['claim_id'], ['summary_claims.claim_id'], ),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['document_chunks.chunk_id'], ),
    sa.ForeignKeyConstraint(['source_condition_id'], ['conditions.condition_id'], ),
    sa.ForeignKeyConstraint(['source_document_id'], ['clinical_documents.document_id'], ),
    sa.ForeignKeyConstraint(['source_medication_id'], ['medications.medication_id'], ),
    sa.ForeignKeyConstraint(['source_observation_id'], ['observations.observation_id'], ),
    sa.ForeignKeyConstraint(['source_report_id'], ['diagnostic_reports.report_id'], ),
    sa.PrimaryKeyConstraint('citation_id')
    )
    op.create_index(op.f('ix_claim_citations_claim_id'), 'claim_citations', ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_citations_claim_id'), table_name='claim_citations')
    op.drop_table('claim_citations')
    op.drop_index(op.f('ix_summary_claims_summary_id'), table_name='summary_claims')
    op.drop_table('summary_claims')
    op.drop_index(op.f('ix_summary_sections_summary_id'), table_name='summary_sections')
    op.drop_table('summary_sections')
    op.drop_index(op.f('ix_summary_reviews_summary_id'), table_name='summary_reviews')
    op.drop_table('summary_reviews')
    op.drop_index(op.f('ix_observations_patient_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_fhir_observation_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_medications_patient_id'), table_name='medications')
    op.drop_index(op.f('ix_medications_fhir_medication_request_id'), table_name='medications')
    op.drop_table('medications')
    op.drop_index(op.f('ix_document_chunks_patient_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index(op.f('ix_diagnostic_reports_patient_id'), table_name='diagnostic_reports')
    op.drop_index(op.f('ix_diagnostic_reports_fhir_diagnostic_report_id'), table_name='diagnostic_reports')
    op.drop_table('diagnostic_reports')
    op.drop_index(op.f('ix_conditions_patient_id'), table_name='conditions')
    op.drop_index(op.f('ix_conditions_fhir_condition_id'), table_name='conditions')
    op.drop_table('conditions')
    op.drop_index(op.f('ix_summaries_patient_id'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_encounter_id'), table_name='summaries')
    op.drop_index('idx_summaries_patient_status', table_name='summaries')
    op.drop_table('summaries')
    op.drop_index(op.f('ix_clinical_documents_patient_id'), table_name='clinical_documents')
    op.drop_index(op.f('ix_clinical_documents_fhir_document_reference_id'), table_name='clinical_documents')
    op.drop_index(op.f('ix_clinical_documents_fhir_composition_id'), table_name='clinical_documents')
    op.drop_index(op.f('ix_clinical_documents_external_document_id'), table_name='clinical_documents')
    op.drop_index(op.f('ix_clinical_documents_encounter_id'), table_name='clinical_documents')
    op.drop_table('clinical_documents')
    op.drop_index(op.f('ix_encounters_patient_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_fhir_encounter_id'), table_name='encounters')
    op.drop_index(op.f('ix_encounters_external_encounter_id'), table_name='encounters')
    op.drop_table('encounters')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_patient_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_logs_timestamp', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_external_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_index(op.f('ix_patients_fhir_patient_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_external_patient_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_table('model_runs')
    # ### end Alembic commands ###
